# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gridprov < Formula
  desc "The Grid Provider CLI — provider onboarding and management"
  homepage "https://theinferencegrid.com"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.0/gridprov_0.1.0_darwin_amd64.tar.gz"
      sha256 "101ca25f4a046e7778b578a49fa290fdd330feccacbcacb786b0789a729e1a2e"

      def install
        bin.install "gridprov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.0/gridprov_0.1.0_darwin_arm64.tar.gz"
      sha256 "f7ce6fc55e3cabf95681296756e330300dae0bbf9fccd3e7d364deccf87a7f3c"

      def install
        bin.install "gridprov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.0/gridprov_0.1.0_linux_amd64.tar.gz"
      sha256 "860002e9404e727ee1ce1b20c1d375cf7ce640ac49b487feced0b8701bd21dd9"
      def install
        bin.install "gridprov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.0/gridprov_0.1.0_linux_arm64.tar.gz"
      sha256 "14e961f595bb3348aa2bfd8da39cd88c57814e1b33fddd1a0aac13b1e04823e7"
      def install
        bin.install "gridprov"
      end
    end
  end

  test do
    system "#{bin}/gridprov", "--version"
  end
end
