# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grid < Formula
  desc "The Grid CLI — lab onboarding and model management"
  homepage "https://theinferencegrid.com"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-AI-Grid/The-Grid/releases/download/v0.1.0/grid_0.1.0_darwin_amd64.tar.gz"
      sha256 "cd93ffa2c42bdcbb9406f1bb85dad3bac6c5fd0dd216ca7f8467e42e83ff7aaa"

      def install
        bin.install "grid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-AI-Grid/The-Grid/releases/download/v0.1.0/grid_0.1.0_darwin_arm64.tar.gz"
      sha256 "4cba1c60369b487017b019e201718ba1922993e3ae8f3f1b8b68d5914e15dac6"

      def install
        bin.install "grid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/The-Grid/releases/download/v0.1.0/grid_0.1.0_linux_amd64.tar.gz"
      sha256 "aefa30cca193d94ef61fefa6c1ab3212754e38cb12224052f766703d56767587"
      def install
        bin.install "grid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/The-Grid/releases/download/v0.1.0/grid_0.1.0_linux_arm64.tar.gz"
      sha256 "ac3c811878dca4545ed8804d2fbc971620bd0bc47f5f64a80d78638aa284147a"
      def install
        bin.install "grid"
      end
    end
  end

  test do
    system "#{bin}/grid", "--version"
  end
end
