# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grid < Formula
  desc "The Grid CLI — lab onboarding and model management"
  homepage "https://theinferencegrid.com"
  version "0.3.4"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.4/grid_0.3.4_darwin_amd64.tar.gz"
      sha256 "9c3a4675eb70ebbb186765aadfafb92baa42bf6ae8159094452602a6358a4898"

      define_method(:install) do
        bin.install "grid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.4/grid_0.3.4_darwin_arm64.tar.gz"
      sha256 "eefea60bdb8fd5ed3599818fbc44e608391316af143caf86026eb2c4f026905b"

      define_method(:install) do
        bin.install "grid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.4/grid_0.3.4_linux_amd64.tar.gz"
      sha256 "281645881b631432c9a16e8e1fc2320db4bd478e6ea2f2f1c9a42ecabba08d50"
      define_method(:install) do
        bin.install "grid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.4/grid_0.3.4_linux_arm64.tar.gz"
      sha256 "b92b1f93516491a4206ffeffb0f49fe50a078e2e15fbc495dc04c457680a5108"
      define_method(:install) do
        bin.install "grid"
      end
    end
  end

  test do
    system "#{bin}/grid", "--version"
  end
end
