# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gridprov < Formula
  desc "The Grid Provider CLI — provider onboarding and management"
  homepage "https://theinferencegrid.com"
  version "0.1.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.1/gridprov_0.1.1_darwin_amd64.tar.gz"
      sha256 "41b0dbcdbd1829cd9231c82f86a01a4b268d04a5277bd4f2d8a88a27f813cc54"

      define_method(:install) do
        bin.install "gridprov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.1/gridprov_0.1.1_darwin_arm64.tar.gz"
      sha256 "ab4079a3ae9b4edc9336d89c83a4aa6fc6e54b60b2013c37d9ef136c5c7dc361"

      define_method(:install) do
        bin.install "gridprov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.1/gridprov_0.1.1_linux_amd64.tar.gz"
      sha256 "71af6b4ab9541799b5d3529709e9ed7fff51b96478a496d394e3a14261682a94"
      define_method(:install) do
        bin.install "gridprov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.1.1/gridprov_0.1.1_linux_arm64.tar.gz"
      sha256 "52be9a7b503d8e6e7d209e256994ef623117417af062543860ae961216bbb4ed"
      define_method(:install) do
        bin.install "gridprov"
      end
    end
  end

  test do
    system "#{bin}/gridprov", "--version"
  end
end
