# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gridprov < Formula
  desc "The Grid Provider CLI — provider onboarding and management"
  homepage "https://theinferencegrid.com"
  version "0.3.5"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.5/gridprov_0.3.5_darwin_amd64.tar.gz"
      sha256 "7389f5d695861503dc52439bf3c01a6bc680d4be013a2704855549086fe53bd0"

      define_method(:install) do
        bin.install "gridprov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.5/gridprov_0.3.5_darwin_arm64.tar.gz"
      sha256 "ec89475e780af00619490da20842bbeac21ca053cbb709f229021df18f9409c8"

      define_method(:install) do
        bin.install "gridprov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.5/gridprov_0.3.5_linux_amd64.tar.gz"
      sha256 "8f2fc9e5837d0b0d596492deb5441a04ef9667519106dd77f4e8f3449d4969a1"
      define_method(:install) do
        bin.install "gridprov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-AI-Grid/grid-cli/releases/download/v0.3.5/gridprov_0.3.5_linux_arm64.tar.gz"
      sha256 "7ebe8fe5070a2feb95c6a890cc7b55690c52539d4091e395c22633a0a6fdd545"
      define_method(:install) do
        bin.install "gridprov"
      end
    end
  end

  test do
    system "#{bin}/gridprov", "--version"
  end
end
